### PR TITLE
Add test case for parallel calls to CalcDDTable

### PR DESCRIPTION
**Pull request by suokko**

### CODE REVIEW

**Comment by suokko** [comment]
I called them hand1 and hand2 to avoid risk of race condition if any called part modifies them. They could be merged if they are read only (which I failed to check).

I will change the variable name.

**Comment by tameware** [comment]
Yes, they are read-only. I should find a way to document that.

**Comment by suokko** [comment]
This has been fixed. It could be merged to keep testing we don't accidentally bring back the old bug.

**Comment by tameware** [comment]
I tested with a range of 1 and it always failed. Increasing the range to 2 slows things down by 1.5 seconds or so, enough to affect a programmer's rhythm. Given that you've already fixed the bug I think it's OK to risk the chance that a stray test run might fail to identify a regression. If you disagree I can live with 2!

**Comment by suokko** [comment]
It depends on what gets broken. If it reverts back to original test then range one with file only if thread start is slower than hand solving. But with data races there is potential cases where only second call allows long enough work queue to trigger some issue. I would say one round and a reasonably fast thread.start catches between 75-90% of data races leading to crash or data corruption.

Of course netiher catches all data races. For a better chance to catch errors libdds would have to be build with thread checker.

**Comment by suokko** [comment]
Over night I had an improed solution. I could find a hand which is much faster to solve so it can be solved twice in both threads. This makes it more likely to find race conditions but tests runs much faster.

Rule to find a fast hand:
* Very balanced shapes for everyone (early discards have a huge impact to the search tree branch count)
* A lot touching cards (touching cards are handled equals reducing branching)
* Every side would mostly take quick tricks in most lines (quick tricks allow early termination for search branches)

I only went with balanced rule making solver run much faster.

**Pull request merged**
